package com.example.music.dao;

import com.example.music.entity.ListSong;

public interface ListSongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated
     */
    int insert(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated
     */
    int insertSelective(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated
     */
    ListSong selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ListSong record);
}