package com.example.music.entity;

public class RankList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_list.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_list.songListId
     *
     * @mbg.generated
     */
    private Long songlistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_list.userId
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_list.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_list.id
     *
     * @return the value of rank_list.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_list.id
     *
     * @param id the value for rank_list.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_list.songListId
     *
     * @return the value of rank_list.songListId
     *
     * @mbg.generated
     */
    public Long getSonglistid() {
        return songlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_list.songListId
     *
     * @param songlistid the value for rank_list.songListId
     *
     * @mbg.generated
     */
    public void setSonglistid(Long songlistid) {
        this.songlistid = songlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_list.userId
     *
     * @return the value of rank_list.userId
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_list.userId
     *
     * @param userid the value for rank_list.userId
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_list.score
     *
     * @return the value of rank_list.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_list.score
     *
     * @param score the value for rank_list.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}